### ISSUE TITLE
support: NX purpose

### ISSUE THREAD

**Issue by djindjic** [waldronmatt/groundwork#216]
# Support Question

Sorry for asking here, but I'm trying to realize why do you need nx here? Can you manage multiple packages in monorepo just by using npm workspaces?

**Comment by waldronmatt** [comment]
You can definitely use npm workspaces instead of nx if that's what you prefer. Both npm workspaces and nx are very similar. However if you want more advanced features like executing a build on only packages that have changed or reuse the outputs of previous builds or tests (caching), then you'll need something more powerful like nx. These features are good for bigger, more complex monorepos. If you have a few packages only and/or don't need those features then npm workspaces is a perfectly suitable option.

**Comment by djindjic** [comment]
Thanks!
